Project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recruitment.urls')),
    path('login/',
         auth_views.LoginView.as_view(template_name='accounts/login.html'),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='accounts/logout.html'),
         name='logout'),
]

recruitment/urls.py
from django.urls import path
from recruitment.views import MainPageView, AddMarkView, CandidatesListView


app_name = 'recruitment'

urlpatterns = [
    path('', MainPageView.as_view(), name='main'),
    path('add-mark/', AddMarkView.as_view(), name='add_mark'),
    path('candidates-list/', CandidatesListView.as_view(), name='candidates-list'),
]

recruitment/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Task(models.Model):
    title = models.TextField()

    def __str__(self):
        return self.title


class Candidate(models.Model):
    first_name = models.TextField(max_length=50)
    last_name = models.TextField(max_length=50)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Grade(models.Model):
    value = models.DecimalField(max_digits=2, decimal_places=1)
    task = models.OneToOneField(Task, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='candidates')
    recruiter = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.candidate} - {self.value}'

recruitment/forms.py
from django import forms
from recruitment.models import Grade


class GradeForm(forms.ModelForm):

    class Meta:
        model = Grade
        fields = ['value', 'task', 'candidate']

recruitment/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render, redirect
from django.views import generic, View
from django.http import JsonResponse
from recruitment.forms import GradeForm
from recruitment.models import Grade

# Create your views here.


class MainPageView(generic.TemplateView):
    template_name = 'index.html'


class AddMarkView(View, PermissionRequiredMixin):
    permission_required = 'recruitment.add_mark'
    template_name = 'add_mark.html'
    form_class = GradeForm

    def get(self, request):
        form = self.form_class(initial={
            'recruiter': request.user.id,
        })
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            grade = form.save(commit=False)
            grade.recruiter = request.user
            grade.save()
            messages.success(request, 'The grade was successfully added')
            return redirect('/')
        return render(request, self.template_name, {'form': form})


class CandidatesListView(View):

    def get(self, request):
        response = []
        ids =[]
        grades = Grade.objects.all()
        for grade in grades:
            if grade.candidate.id in ids:
                pass
            else:
                avg = float(sum([grade.value for grade in Grade.objects.filter(candidate_id=grade.candidate.id)])\
                                / Grade.objects.filter(candidate_id=grade.candidate.id).count())
                response.append({
                    "pk": grade.candidate.id,
                    "full_name": grade.candidate.first_name + ' ' + grade.candidate.last_name,
                    "grades": [float(grade.value) for grade in Grade.objects.filter(candidate_id=grade.candidate.id)],
                    "avg_grade": round(avg, 2),

                })
                ids.append(grade.candidate.id)
        return JsonResponse(response, safe=False)

templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
       <form method="POST">
           {% csrf_token %}
           <fieldset class="form-group">
               <legend class="border-bottom mb-4">Log In</legend>
               {{ form|crispy }}
           </fieldset>
           <div class="form-group">
               <button class="btn btn-outline-info" type="submit">Login</button>
           </div>
       </form>
{% endblock content %}

templates/accounts/logout.html
{% extends 'base.html' %}
{% block content %}
   <h2>You have been logged out</h2>
   <div class="border-top pt-3">
       <small class="text-muted">
           <a href="{% url 'login' %}">Log in Again</a>
       </small>
   </div>
{% endblock content %}

templates/add_mark.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
       <form method="POST">
           {% csrf_token %}
           <fieldset class="form-group">
               <legend class="border-bottom mb-4">Add mark</legend>
               {{ form|crispy }}
           </fieldset>
           <div class="form-group">
               <button class="btn btn-outline-info" type="submit">Add</button>
           </div>
       </form>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
   <title>Recruitment</title>
</head>

<body>
   <header class="site-header">
     <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
       <div class="container">
         <a class="navbar-brand mr-4" href="{% url 'recruitment:main' %}">Recruitment</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarToggle">
           <div class="navbar-nav mr-auto">
               {% if user.is_authenticated %}
             <a class="nav-item nav-link" href="{% url 'recruitment:main' %}">Home</a>
             <a class="nav-item nav-link" href="{% url 'recruitment:add_mark' %}">Add mark</a>
             <a class="nav-item nav-link" href="{% url 'recruitment:candidates-list' %}">Candidates list</a>
             <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            <h10>Logged as: {{ request.user }}</h10>
               {% else %}
            <a class="nav-item nav-link" href="{% url 'recruitment:main' %}">Home</a>
             <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
               {% endif %}
           </div>
         </div>
       </div>
     </nav>
   </header>
    <main role="main" class="container">
   {% block content %}
   {% endblock %}
    </main>
   <!-- Optional JavaScript -->
   <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
     {% if messages %}
        {% for message in messages %}
            <font color="red">{{ message }}</font>
        {% endfor %}
    {% endif %}
{% endblock content %}